- name: msd-reportes-ms
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/ofipensiones-443615/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/cos-cloud/global/images/cos-101-17162-463-16
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/ofipensiones-443615/global/networks/default
      networkIP: 10.128.0.86
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - msd-services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt install python3-pip -y
          sudo mkdir /home/proyecto
          cd /home/proyecto
          sudo git clone https://github.com/JairoFierro/Sprint4.git
          cd Sprint4/reportes
          sudo pip3 install -r requeriments.txt
          sudo python3 manage.py makemigrations
          sudo python3 manage.py migrate